### ISSUE TITLE
Make API Key Handling more robust

### ISSUE THREAD

**Issue by dogeared** [dogeared/ctfd-account-hook#5]
Currently, an API Key is verified off of an environment variable setting. Ideally, this would be more secure. 

https://github.com/dogeared/ctfd-account-hook/blob/main/src/main/java/dev/dogeared/ctfdaccounthook/service/ApiKeyAuthenticationServiceImpl.java#L17

At the very least, it should be a salted hash. It might be better stored in a database and, potentially have support for expiration and revoking.

**Comment by Monoradioactivo** [comment]
@dogeared I have created a pull request for this issue. Please review and provide feedback! https://github.com/dogeared/ctfd-account-hook/pull/6
